# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '追书神器' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 追书神器
pod 'AFNetworking'
pod 'MJRefresh'
pod 'SDWebImage', '3.8'
pod 'MBProgressHUD'

end
